import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import { Inter } from 'next/font/google';
import type { PropsWithChildren } from 'react';

import BackToTop from '@/components/BackTop';

import '@/styles/index.css';

const inter = Inter({ subsets: ['latin'] });
const ThemeProvider = dynamic(() => import('@/app/(main)/ThemeProvider'), {
  ssr: false,
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='zh-CN'>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='light'
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <BackToTop />
        </ThemeProvider>
      </body>
    </html>
  );
}
